name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'
      - run: yarn install
        
      - name: Run linters
        uses: samuelmeuli/lint-action@v1.5.2
        with:
          eslint: true
          prettier: true
          
      - name: Publish to NPM
      - uses: actions/setup-node@v1.4.2
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
